#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/file
#
# IDENTIFICATION
#    src/backend/storage/file/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/storage/iostack
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

# Make this conditional on iostack option
OBJS = \
	iostack_top.c \
	vfd_bottom.c

include $(top_srcdir)/src/backend/common.mk
