#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/iostack
#
# IDENTIFICATION
#    src/backend/storage/iostack/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/storage/iostack
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

# Make this conditional on iostack option
OBJS = \
	iostack_top.o \
	vfd_bottom.o

include $(top_srcdir)/src/backend/common.mk
